### ISSUE TITLE
cmake version issue and build erros for minzip-ng

### ISSUE THREAD

**Issue by S-Streit** [RationAI/pathopus-docker#4]
First issue is CheckSourceCompiles not found by inlcude in CMakeLists.txt of minizip-ng
Can be fixed by installing latest version of cmake
See related Issue
[Minzip Issue 720](https://github.com/zlib-ng/minizip-ng/issues/720)

Second issue is with minizip-ng version 4.0

It seems there is a argument error within the 4.0 source / building from 3.0.10 works 
See issue:
[Build error on Ubuntu 20.04](https://github.com/zlib-ng/minizip-ng/issues/724)

**Comment by Aiosa** [comment]
Thanks for the echo! We fetch the latest minizip code so this breaks things as the lib introduced breaking changes in its API. I will update it to fetch a specific commit instead.

**Comment by Aiosa** [comment]
Should be fixed with https://github.com/RationAI/xopat-docker/commit/ff37cb6cab2fdae29751565b0fbff74823e79fc8. Thanks again.
