### ISSUE TITLE
404 not found on initial install/redirect

### ISSUE THREAD

**Issue by MartinKlefas** [RationAI/pathopus-docker#5]
I think I've followed [the instructions for the basic setup](https://github.com/RationAI/xopat-docker/tree/main/templates/basic), but when i go to http://localhost:8080 it redirects me to http://localhost:8080/authorized/cases/path/ and that gives a 404 error.

Should I be running something alongside this to serve cases or similar?

**Comment by Aiosa** [comment]
Hi, as noted in the main readme:

> We are currently unable to maintain compatibility of this deployment example. We are preparing advanced architecture, viewer features and deployment options.

The URL you are seeing is actually a valid URL for the new case viewer we've developed. I will try to update the demo as soon as I can, hovewer, I am afraid our priorities are for now elsewhere. I am actually surprised you are getting the redirection, that should not happen - I can at least try to figure out where that is comming from.

If I can help with anything regarding the deployment, please, let me know. It should not be that difficult to deploy the viewer on its own, and connect it to whatver WSI server you are using. It will be a bit harder if the server uses priprietary protocols, but there are eaxmples in the viewer repository on how to program custom ones as well.

**Comment by Aiosa** [comment]
Also, if you would like to try out the new infrastructure, we have a public testing deployment available. If you are interested in trying that, I can arrange a setup - just PM me. Since we are unable to provide an open demo for now here, and since you are showing an interest in our work ❤️

**Comment by MartinKlefas** [comment]
> whatever WSI server you are using

We don't have a server preference at the moment - which is why I'd gone for the whole package deployment over just the viewer. I'd actually tried building your server and your viewer in my own docker-compose additions to your php version before discovering this repo.

I had to steal the tip on using a lower version of minizip-ng and the cmake settings from your compose file, but interestingly that's giving a different error - instead booting to a data not found screen:
![screenshot of alternative compose](https://github.com/RationAI/xopat-docker/assets/12558370/fbead286-7750-4464-a45c-8e33d744b58e)

I'll ping you a PM though, as a demo would be great.

**Comment by MartinKlefas** [comment]
Actually - I tried to implement your iipsrv branch, and have just noticed your [WSI-Service](https://github.com/RationAI/WSI-Service) - that looks like a great option if it'll pair with the xopat viewer?

**Comment by Aiosa** [comment]
Yes, the newer server we try to maintain should be much more feature-rich option. Please check here https://github.com/RationAI/xopat/issues/54.

The 'error' you are seeing is probably just the viewer complaining that you did not say what to view. To do so, you have to
 - provide the session configuration manually, e.g. via `/dev_setup`
 - use a different app that will generate these sessions for you
    - e.g. build a script that generates a HTML page with links that contain the data specification

The server might be indeed not responding, that's also an option, there might be problems with the configuration (did you configure xOpat with default imaging protocol to use?) and the server itself (is it deployed correctly?).
 
This is actually the only blocking chain piece that I am missing in deploying a V2 version of the docker compose demo. We do have a viewer able to open xOpat sessions, but it cannot talk to the WSI Service yet.

**Comment by MartinKlefas** [comment]
I've had a look at /dev_setup and while I've added my images to `/images/` in the docker container and have `/images/1.ndpi` as my test case I'm not sure quite how to change the json to get it pointing at my example folder or file? The below doesn't work:

`{
    "params": {
        "customBlending": true
    },
    "data": [],
    "background": [
        {
            "dataReference": 1,
            "lossless": false
        }
    ],
    "visualizations": [
        {
            "name": "A visualization setup 1",
            "lossless": true,
            "shaders": {
                "shader_id_1": {
                    "name": "Layer 1",
                    "type": "identity",
                    "visible": 1,
                    "fixed": false,
                    "dataReferences": ["/images/1.ndpi"],
                    "params": { }
                }
            }
        }
    ]
}
`

it says:
`JSON parametrization of the visualizer requires valid dataReference for each background layer.
Invalid data reference value '1'. Available data: []`

I think perhaps I'm swimming in water too deep for me, and I'll need to wait for an idiots guide. I got the Mirax server running from the code here - so if there's a way to upload and then view based on that?

**Comment by Aiosa** [comment]
You are saying that the background image should be a data of index `1`. You provide data `"data": []`.

Correct JSON:
```
{
    "params": {
        "customBlending": true
    },
    "data": ["images/1.ndpi"],
    "background": [
        {
            "dataReference": 0,
            "lossless": false
        }
    ]
}
```
If you want to create visualization layer, you can do:
````
{
    "params": {
        "customBlending": true
    },
    "data": ["images/1.ndpi"],
    "visualizations": [
        {
            "name": "A visualization setup 1",
            "lossless": true,
            "shaders": {
                "shader_id_1": {
                    "name": "Layer 1",
                    "type": "identity",
                    "visible": 1,
                    "fixed": false,
                    "dataReferences": [0]
                }
            }
        }
    ]
}
````
However, this supposes that
 - the viewer is set up correctly, e.g. `env.json` knows how to ask the server for data (WSI Service has the module enabled and configured)
 - the servier is capable of NDPI

**Comment by Aiosa** [comment]
This is meant for programs as API, not people to create manually. I've sent demo link to your email.

**Comment by MartinKlefas** [comment]
Thank you, the demo is great.
